sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t wrhen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wrhen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-884245076799"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
